Add build deploy file
fabric8-analytics/fabric8-analytics-pgbouncer pull request #64
Opened 2021-09-28 14:07 UTC by AkshayBhansali18

Add build deploy file

2021-09-28 14:35 UTC, yzainee commented
LGTM. @sawood14012 PTAL

2021-09-28 15:17 UTC, sawood14012 commented
If you see there is a rhel based docker file also present so you may have to also make one deploy file for (prod) based on rhel 

Ref: worker for example

2021-09-28 15:18 UTC, sawood14012 requested changes
Add rhel based deploy file .

2021-09-29 05:11 UTC, rafiu007 approved these changes

2021-10-06 11:39 UTC, sawood14012 approved these changes

2021-10-06 11:45 UTC, merged